apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gxppft99u-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:5dda8fd6d71905bc810c11bd95d7dbf0fc318e78@sha256:4df1eb3ef0ce6359727c72cbc270f7714e5b5fd9e66e0e632b0ed8bf96a984c9
          name: container-image
